// Mapeamento de itens disponíveis
const items = {
    // TMs
    'bug': require('./items/tms/tm-bug.png'),
    'dark': require('./items/tms/tm-dark.png'),
    'dragon': require('./items/tms/tm-dragon.png'),
    'electric': require('./items/tms/tm-electric.png'),
    'fighting': require('./items/tms/tm-fighting.png'),
    'fire': require('./items/tms/tm-fire.png'),
    'flying': require('./items/tms/tm-flying.png'),
    'ghost': require('./items/tms/tm-ghost.png'),
    'grass': require('./items/tms/tm-grass.png'),
    'ground': require('./items/tms/tm-ground.png'),
    'ice': require('./items/tms/tm-ice.png'),
    'normal': require('./items/tms/tm-normal.png'),
    'poison': require('./items/tms/tm-poison.png'),
    'psychic': require('./items/tms/tm-psychic.png'),
    'rock': require('./items/tms/tm-rock.png'),
    'steel': require('./items/tms/tm-steel.png'),
    'water': require('./items/tms/tm-water.png'),
    
    // ... adicionar mais TMs conforme necessário

    // Plates
    'dread-plate': require('./items/plates/dread-plate.png'),
    'earth-plate': require('./items/plates/earth-plate.png'),
    'fist-plate': require('./items/plates/fist-plate.png'),
    'flame-plate': require('./items/plates/flame-plate.png'),
    'icicle-plate': require('./items/plates/icicle-plate.png'),
    'insect-plate': require('./items/plates/insect-plate.png'),
    'iron-plate': require('./items/plates/iron-plate.png'),
    'meadow-plate': require('./items/plates/meadow-plate.png'),
    'mind-plate': require('./items/plates/mind-plate.png'),
    'sky-plate': require('./items/plates/sky-plate.png'),
    'splash-plate': require('./items/plates/splash-plate.png'),
    'spooky-plate': require('./items/plates/spooky-plate.png'),
    'stone-plate': require('./items/plates/stone-plate.png'),
    'toxic-plate': require('./items/plates/toxic-plate.png'),
    'zap-plate': require('./items/plates/zap-plate.png'),

    // Mega Stones
    'abomasite': require('./items/mega-stones/abomasite.png'),
    'absolite': require('./items/mega-stones/absolite.png'),
    'aerodactylite': require('./items/mega-stones/aerodactylite.png'),
    'aggronite': require('./items/mega-stones/aggronite.png'),
    'alakazite': require('./items/mega-stones/alakazite.png'),
    'altarianite': require('./items/mega-stones/altarianite.png'),
    'ampharosite': require('./items/mega-stones/ampharosite.png'),
    'audinite': require('./items/mega-stones/audinite.png'),
    'banettite': require('./items/mega-stones/banettite.png'),
    'beedrillite': require('./items/mega-stones/beedrillite.png'),
    'blastoisinite': require('./items/mega-stones/blastoisinite.png'),
    'blazikenite': require('./items/mega-stones/blazikenite.png'),
    'cameruptite': require('./items/mega-stones/cameruptite.png'),
    'charizardite-x': require('./items/mega-stones/charizardite-x.png'),
    'charizardite-y': require('./items/mega-stones/charizardite-y.png'),
    'diancite': require('./items/mega-stones/diancite.png'),
    'galladite': require('./items/mega-stones/galladite.png'),
    'garchompite': require('./items/mega-stones/garchompite.png'),
    'gardevoirite': require('./items/mega-stones/gardevoirite.png'),
    'gengarite': require('./items/mega-stones/gengarite.png'),
    'glalitite': require('./items/mega-stones/glalitite.png'),
    'gyaradosite': require('./items/mega-stones/gyaradosite.png'),
    'heracronite': require('./items/mega-stones/heracronite.png'),
    'houndoominite': require('./items/mega-stones/houndoominite.png'),
    'kangaskhanite': require('./items/mega-stones/kangaskhanite.png'),
    'latiasite': require('./items/mega-stones/latiasite.png'),
    'latiosite': require('./items/mega-stones/latiosite.png'),
    'lopunnite': require('./items/mega-stones/lopunnite.png'),
    'lucarionite': require('./items/mega-stones/lucarionite.png'),
    'manectite': require('./items/mega-stones/manectite.png'),
    'mawilite': require('./items/mega-stones/mawilite.png'),
    'medichamite': require('./items/mega-stones/medichamite.png'),
    'metagrossite': require('./items/mega-stones/metagrossite.png'),
    'mewtwonite-x': require('./items/mega-stones/mewtwonite-x.png'),
    'mewtwonite-y': require('./items/mega-stones/mewtwonite-y.png'),
    'pidgeotite': require('./items/mega-stones/pidgeotite.png'),
    'pinsirite': require('./items/mega-stones/pinsirite.png'),
    'sablenite': require('./items/mega-stones/sablenite.png'),
    'salamencite': require('./items/mega-stones/salamencite.png'),
    'sceptilite': require('./items/mega-stones/sceptilite.png'),
    'scizorite': require('./items/mega-stones/scizorite.png'),
    'sharpedonite': require('./items/mega-stones/sharpedonite.png'),
    'slowbronite': require('./items/mega-stones/slowbronite.png'),
    'steelixite': require('./items/mega-stones/steelixite.png'),
    'swampertite': require('./items/mega-stones/swampertite.png'),
    'tyranitarite': require('./items/mega-stones/tyranitarite.png'),
    'venusaurite': require('./items/mega-stones/venusaurite.png'),

    // Evolution Items
    'dragon-scale': require('./items/evolution/dragon-scale.png'),
    'dubious-disc': require('./items/evolution/dubious-disc.png'),
    'electirizer': require('./items/evolution/electirizer.png'),
    'kings-rock': require('./items/evolution/kings-rock.png'),
    'magmarizer': require('./items/evolution/magmarizer.png'),
    'metal-coat': require('./items/evolution/metal-coat.png'),
    'protector': require('./items/evolution/protector.png'),
    'razor-claw': require('./items/evolution/razor-claw.png'),
    'razor-fang': require('./items/evolution/razor-fang.png'),
    'reaper-cloth': require('./items/evolution/reaper-cloth.png'),
    'sachet': require('./items/evolution/sachet.png'),
    'up-grade': require('./items/evolution/up-grade.png'),
    'whipped-dream': require('./items/evolution/whipped-dream.png'),
};

export default items; 